import os
import subprocess
import time

import httpx
import pytest


def test_uvicorn_root_path_integration():
    """
    Test that UVICORN_ROOT_PATH environment variable is correctly picked up by Uvicorn
    and reflected in the links generated by url_for in the templates.
    """
    port = 8082
    root_path = "/integration-test-prefix"

    env = os.environ.copy()
    env["UVICORN_ROOT_PATH"] = root_path
    env["UVICORN_PORT"] = str(port)
    env["UVICORN_HOST"] = "127.0.0.1"

    # Start uvicorn process
    # We use "uv run uvicorn" to ensure we are using the correct environment
    proc = subprocess.Popen(
        ["uv", "run", "uvicorn", "app.main:app"],
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )

    try:
        # Wait for the server to start (polling)
        max_retries = 20
        response = None
        for i in range(max_retries):
            try:
                response = httpx.get(f"http://127.0.0.1:{port}/")
                if response.status_code == 200:
                    break
            except httpx.RequestError:
                pass
            time.sleep(0.5)

        if response is None or response.status_code != 200:
            stdout, stderr = proc.communicate(timeout=1)
            pytest.fail(
                "Uvicorn failed to start or respond. "
                f"STDOUT: {stdout}, STDERR: {stderr}"
            )

        # Verify that the links in the HTML contain the root_path
        assert f"{root_path}/" in response.text

    finally:
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()
